module(
    name = "rules_detekt_compat_v1",
    version = "0.0.0",
)

bazel_dep(name = "rules_detekt", version = "0.0.0", dev_dependency = True)

bazel_dep(name = "bazel_skylib", version = "1.8.2")
bazel_dep(name = "rules_kotlin", version = "2.4.0")

local_path_override(
    module_name = "rules_detekt",
    path = "../..",
)

detekt = use_extension(
    "@rules_detekt//detekt:extensions.bzl",
    "detekt",
)
detekt.detekt_version(
    sha256 = "2ce2ff952e150baf28a29cda70a363b0340b3e81a55f43e51ec5edffc3d066c1",
    version = "1.23.8",
)
use_repo(detekt, "detekt_cli_all")
